apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
  labels:
    app.kubernetes.io/name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        version: v-2206-07-20
        deploy: d-22-06-07-20-59-43
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: app
          image: ghcr.io/retaildevcrews/myapp:latest
          imagePullPolicy: Always

          args:
          - --zone
          - pibtt
          - --region
          - pibtt

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
